-- AlterTable
ALTER TABLE `arquivos` MODIFY `categoria` ENUM('CAND_ENT_REQUERIMENTO', 'CAND_ENT_DECLARACAO_ATUACAO', 'CAND_ENT_ESTATUTO', 'CAND_ENT_ATA_ELEICAO', 'CAND_ENT_CNPJ', 'CAND_ENT_DECLARACAO_IDONEIDADE', 'CAND_REP_IDENTIDADE', 'CAND_REP_TITULO_ELEITOR', 'CAND_REP_CPF', 'CAND_REP_FOTO', 'CAND_REP_NAO_IMPEDIMENTO', 'CAND_CHAPA_REQUERIMENTO', 'ELEIT_ENT_REQUERIMENTO', 'ELEIT_ENT_DECLARACAO_ATUACAO', 'ELEIT_ENT_ESTATUTO', 'ELEIT_ENT_ATA_ELEICAO', 'ELEIT_ENT_CNPJ', 'ELEIT_ENT_DECLARACAO_IDONEIDADE', 'ELEIT_REP_IDENTIDADE', 'ELEIT_REP_TITULO_ELEITOR', 'ELEIT_REP_CPF', 'ELEIT_PROC_PROCURACAO', 'ELEIT_PROC_REQUERIMENTO', 'COMPLEMENTAR') NOT NULL;

-- AlterTable
ALTER TABLE `candidaturas` MODIFY `status` ENUM('EM_ANALISE', 'DEFERIDO', 'INDEFERIDO', 'AGUARDANDO_DOCUMENTACAO') NOT NULL DEFAULT 'EM_ANALISE';

-- AlterTable
ALTER TABLE `eleitores` MODIFY `status` ENUM('EM_ANALISE', 'DEFERIDO', 'INDEFERIDO', 'AGUARDANDO_DOCUMENTACAO') NOT NULL DEFAULT 'EM_ANALISE';
