-- AlterTable
ALTER TABLE `inscricoes` ADD COLUMN `atualizadoEm` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `criadoEm` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `representantes` ADD COLUMN `nomeEmpresa` VARCHAR(191) NULL,
    ADD COLUMN `nomeSocial` VARCHAR(191) NULL;
