-- AlterTable: adiciona novos valores ao enum CategoriaArquivo
ALTER TABLE `arquivos` MODIFY COLUMN `categoria` ENUM(
  'REQUERIMENTO',
  'DOCUMENTO_IDENTIDADE',
  'CPF',
  'TITULO_ELEITOR',
  'COMPROVANTE_RESIDENCIA',
  'COMPROVANTE_TRABALHO',
  'FOTO',
  'DECLARACAO',
  'DECLARACAO_ATUACAO',
  'ESTATUTO_SOCIAL',
  'ATA_ELEICAO',
  'CERTIDAO_CNPJ',
  'DECLARACAO_IDONEIDADE',
  'REQUERIMENTO_ENTIDADE_ELEITORA',
  'REQUERIMENTO_CHAPA',
  'OUTRO'
) NOT NULL;
