-- AlterTable
ALTER TABLE `arquivos` MODIFY `categoria` ENUM('REQUERIMENTO', 'DOCUMENTO_IDENTIDADE', 'CPF', 'TITULO_ELEITOR', 'COMPROVANTE_RESIDENCIA', 'COMPROVANTE_TRABALHO', 'FOTO', 'DECLARACAO', 'DECLARACAO_ATUACAO', 'ESTATUTO_SOCIAL', 'ATA_ELEICAO', 'CERTIDAO_CNPJ', 'DECLARACAO_IDONEIDADE', 'REQUERIMENTO_ENTIDADE_ELEITORA', 'REQUERIMENTO_CHAPA', 'OUTRO', 'COMPLEMENTAR') NOT NULL;

-- AlterTable
ALTER TABLE `inscricoes` MODIFY `status` ENUM('EM_ANALISE', 'DEFERIDO', 'INDEFERIDO', 'AGUARDANDO_DOCUMENTACAO') NOT NULL DEFAULT 'EM_ANALISE';
